import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Sidebar } from "./component/sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const navItems = [
  { title: "Dashboard", path: "/", image: "globe.svg" },
  { title: "Profile", path: "/profile", image: "file.svg" },
  { title: "Settings", path: "/settings", image: "vercel.svg" },
  { title: "Help", path: "/help", image: "window.svg" },
];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex">
          {/* <Sidebar navItems={navItems} /> */}
          <main className="flex-1 p-6">{children}</main>
        </div>
      </body>
    </html>
  );
}
